name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build & deploy
      run: |
        git config --global user.name "Krzysztof Stozek"
        git config --global user.email "krzys1u@github.com"
        npm ci
        npm run build
        npm run deploy --user='Krzysztof Stozek <stozekrzysztof@gmail.com>' --repo=https://$TOKEN@github.com/krzys1u/salaryComparer.git

      env:
        CI: true
